// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {main} from '../models';
import {hwinfo} from '../models';
import {system} from '../models';
import {netinfo} from '../models';
import {proc} from '../models';
import {services} from '../models';
import {logs} from '../models';
import {health} from '../models';
import {storage} from '../models';

export function CancelHealthCheck():Promise<void>;

export function DiscoverProjects():Promise<Array<project.Project>>;

export function ForgetProject(arg1:string):Promise<main.Settings>;

export function GetBattery():Promise<hwinfo.Battery>;

export function GetGeometry():Promise<main.Geometry>;

export function GetHost():Promise<system.HostInfo>;

export function GetMachineReport():Promise<hwinfo.Report>;

export function GetProjectState(arg1:string):Promise<main.ProjectState>;

export function GetSettings():Promise<main.Settings>;

export function GetSnapshot():Promise<system.Snapshot>;

export function HomeDir():Promise<string>;

export function IsMaximised():Promise<boolean>;

export function KillProcess(arg1:number,arg2:string):Promise<void>;

export function ListConnections():Promise<Array<netinfo.Conn>>;

export function ListPorts():Promise<Array<netinfo.Conn>>;

export function ListProcesses():Promise<Array<proc.Info>>;

export function ListServices():Promise<Array<services.Service>>;

export function LogSources():Promise<Array<logs.Source>>;

export function LogStart(arg1:string,arg2:logs.Source):Promise<void>;

export function LogStop(arg1:string):Promise<void>;

export function Minimise():Promise<void>;

export function OpenProject(arg1:string):Promise<project.Project>;

export function OpenURL(arg1:string):Promise<void>;

export function PickProject():Promise<string>;

export function ProcessDetail(arg1:number):Promise<proc.Detail>;

export function Quit():Promise<void>;

export function RunHealthCheck():Promise<Array<health.Check>>;

export function RunScript(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ScanPath(arg1:string):Promise<storage.ScanResult>;

export function ServiceAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ServiceLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetGeometry(arg1:main.Geometry):Promise<void>;

export function SetPollInterval(arg1:number):Promise<void>;

export function TermClose(arg1:string):Promise<void>;

export function TermResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TermStart(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function TermWrite(arg1:string,arg2:string):Promise<void>;

export function ToggleMaximise():Promise<void>;

export function Version():Promise<string>;
