// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverProjects() {
  return window['go']['main']['App']['DiscoverProjects']();
}

export function ForgetProject(arg1) {
  return window['go']['main']['App']['ForgetProject'](arg1);
}

export function GetGeometry() {
  return window['go']['main']['App']['GetGeometry']();
}

export function GetHost() {
  return window['go']['main']['App']['GetHost']();
}

export function GetProjectState(arg1) {
  return window['go']['main']['App']['GetProjectState'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function IsMaximised() {
  return window['go']['main']['App']['IsMaximised']();
}

export function KillProcess(arg1, arg2) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function LogSources() {
  return window['go']['main']['App']['LogSources']();
}

export function LogStart(arg1, arg2) {
  return window['go']['main']['App']['LogStart'](arg1, arg2);
}

export function LogStop(arg1) {
  return window['go']['main']['App']['LogStop'](arg1);
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickProject() {
  return window['go']['main']['App']['PickProject']();
}

export function ProcessDetail(arg1) {
  return window['go']['main']['App']['ProcessDetail'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScript'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanPath(arg1) {
  return window['go']['main']['App']['ScanPath'](arg1);
}

export function ServiceAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceAction'](arg1, arg2, arg3);
}

export function ServiceLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceLogs'](arg1, arg2, arg3);
}

export function SetGeometry(arg1) {
  return window['go']['main']['App']['SetGeometry'](arg1);
}

export function SetPollInterval(arg1) {
  return window['go']['main']['App']['SetPollInterval'](arg1);
}

export function TermClose(arg1) {
  return window['go']['main']['App']['TermClose'](arg1);
}

export function TermResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TermResize'](arg1, arg2, arg3);
}

export function TermStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TermStart'](arg1, arg2, arg3, arg4);
}

export function TermWrite(arg1, arg2) {
  return window['go']['main']['App']['TermWrite'](arg1, arg2);
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}
